import PartaiInfo from '../models/PartaiInfo.js';
import dotenv from 'dotenv';
dotenv.config();

const partaiInfoData = [
  {
    name: 'Partai Kebangkitan Bangsa (PKB)',
    no_urut: 1,
    ig_sosmed: 'https://www.instagram.com/pkb_id/',
    fb_sosmed: 'https://www.facebook.com/pkb.id/',
    x_sosmed: '',
    website: 'https://pkb.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Kebangkitan_Bangsa',
    deskripsi:"Partai Kebangkitan Bangsa (PKB), adalah sebuah partai politik berideologi Moderat di Indonesia. Partai ini didirikan di Jakarta pada tanggal 23 Juli 1998 (29 Rabi'ul Awal 1419 Hijriah) yang dideklarasikan oleh para kiai-kiai Nahdlatul Ulama, seperti Munasir Ali, Ilyas Ruhiat, Abdurrahman Wahid, Mustofa Bisri, Zuhdi Fatkur dan Muhith Muzadi.",
    koalisi:'Perubahan',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656538128_Logo%20PKB.png',
    usungPaslon: 1,
  },
  {
    name: 'Partai Gerakan Indonesia Raya (Gerindra)',
    no_urut: 2,
    ig_sosmed: 'https://instagram.com/gerindra/',
    fb_sosmed: 'https://www.facebook.com/PartaiGerindra/',
    x_sosmed: 'https://twitter.com/Gerindra/',
    website: 'https://gerindra.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Gerakan_Indonesia_Raya',
    deskripsi:"Partai Gerakan Indonesia Raya (Gerindra) adalah sebuah partai politik di Indonesia. Dibentuk pada tahun 2008, Gerindra berfungsi sebagai kendaraan politik mantan jenderal Prabowo Subianto. Saat ini, Gerindra adalah partai ketiga terbesar di DPR berdasarkan hasil perolehan suara dalam pemilu legislatif 2019 dengan 78 kursi.\nPada kurun waktu 2008 hingga 2019, Gerindra memosisikan diri sebagai partai oposisi. Pasca pemilu 2019, Gerindra bergabung dengan Kabinet Indonesia Maju dibawah pimpinan Presiden Joko Widodo, meskipun sebelumnya Prabowo pernah menghadapi Joko Widodo dalam pemilihan presiden pada 2014 dan 2019",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1657710596_Logo%20GERINDRA%2010x10.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Demokrasi Indonesia Perjuangan (PDI-P)',
    no_urut: 3,
    ig_sosmed: 'https://instagram.com/pdiperjuangan',
    fb_sosmed: 'https://www.facebook.com/PDI.Perjuangan.Official/',
    x_sosmed: 'https://twitter.com/PDIPerjuangan',
    website: 'https://pdiperjuangan.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Demokrasi_Indonesia_Perjuangan',
    deskripsi:"Partai Demokrasi Indonesia Perjuangan (PDI-P) adalah sebuah partai politik Indonesia, dan partai  dari Presiden Indonesia saat ini, Joko Widodo. PDI-P saat ini dipimpin oleh Megawati Soekarnoputri, Presiden Kelima Indonesia, dan merupakan putri dari Presiden Pertama Indonesia Soekarno.\nIdeologi partai didasarkan pada filosofi nasional resmi Indonesia, yaitu Pancasila.",
    koalisi:'Kerja Sama',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656305039_LOGO%20PDI%20PERJUANGAN.png',
    usungPaslon: 3,
  },
  {
    name: 'Partai Golongan Karya (Golkar)',
    no_urut: 4,
    ig_sosmed: 'https://www.instagram.com/golkar.indonesia/',
    fb_sosmed: 'https://www.facebook.com/golkar.indonesia/',
    x_sosmed: 'https://twitter.com/golkar_id/',
    website: 'https://www.partaigolkar.com/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Golongan_Karya',
    deskripsi:"Partai Golongan Karya atau secara umum disingkat dengan Partai Golkar adalah sebuah partai politik di Indonesia. Didirikan sebagai Sekretariat Bersama Golongan Karya (Sekber Golkar) pada tahun 1964, dan berpartisipasi untuk pertama kalinya dalam pemilihan umum nasional pada 1971 sebagai Golkar (Golongan Karya). Partai Golongan Karya tidak resmi menjadi partai politik hingga tahun 1999, ketika Golkar diperlukan untuk menjadi sebuah partai untuk mengikuti pemilihan.\nPartai Golkar berkuasa dari tahun 1971 hingga 1999, di bawah kepemimpinan Presiden Soeharto dan B.J. Habibie. Kemudian bergabung dengan koalisi yang berkuasa di bawah presiden Abdurrahman Wahid, Megawati Soekarnoputri, dan Susilo Bambang Yudhoyono.  Ketika Presiden Joko Widodo dari PDI-P terpilih pada tahun 2014, Partai Golongan Karya awalnya memilih untuk bergabung dengan koalisi oposisi yang dipimpin oleh mantan jenderal Prabowo Subianto, yang pada akhirnya kembali mengalihkan dukungannya kepada Pemerintahan yang dipimpin oleh Presiden Joko Widodo pada tahun 2016.Dalam perkembangannya, khususnya pasca Orde Baru, Partai Golkar berhasil bertransformasi menjadi partai modern yang mengadopsi nilai-nilai demokrasi. Pimpinan-pimpinan Partai Golkar juga berhasil menahkodai Golkar sebagai partai politik berpaham sentrisme yang merangkul semua golongan dengan mengedepankan semangat moderat.",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656586681_Logo%20Golkar.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Nasional Demokrat (NasDem)',
    no_urut: 5,
    ig_sosmed: 'https://www.instagram.com/official_nasdem/',
    fb_sosmed: 'https://www.facebook.com/OfficialNasDem/',
    x_sosmed: 'https://twitter.com/NasDem',
    website: 'https://nasdem.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Nasional_Demokrat',
    deskripsi:"Partai Nasional Demokrat dapat mengacu pada beberapa hal berikut: Partai Nasional Demokrat (1998), partai politik Indonesia yang didirikan pada tahun 1998 dan mengikuti pemilihan umum pertamanya pada tahun 1999. Partai Nasional Demokrat (2011), atau secara umum disingkat dengan Partai NasDem adalah partai politik Indonesia yang didirikan pada tahun 2011 dan mengikuti pemilihan umum pertamanya pada tahun 2014\nPartai Nasional Demokrat Jerman, partai politik Jerman yang didirikan pada tahun 1964 dan mengikuti pemilihan umum pertamanya pada tahun 1965",
    koalisi:'Perubahan',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656224727_Logo%20NasDem%20KPU.png',
    usungPaslon: 1,
  },
  {
    name: 'Partai Buruh',
    no_urut: 6,
    ig_sosmed: 'https://www.instagram.com/partaiburuh_/',
    fb_sosmed: 'https://www.facebook.com/partaiburuh.official/',
    x_sosmed: 'https://twitter.com/EXCOPARTAIBURUH',
    website: 'https://partaiburuh.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Buruh_(Indonesia,_1998)',
    deskripsi:"Partai Buruh adalah sebuah partai politik di Indonesia yang didirikan pertama kali pada tanggal 28 Agustus 1998. Partai politik ini pernah menjadi peserta Pemilu 1999, Pemilu 2004, dan Pemilu 2009. Selama menjadi partai politik, Partai Buruh telah menggunakan tiga nama yang berbeda, yaitu Partai Buruh Nasional (1998), Partai Buruh Sosial Demokrat (2003) dan Partai Buruh (2008). Pada 2021, di bawah inisiatif serikat-serikat buruh nasional, Partai Buruh bertransformasi menjadi Partai Buruh dengan identitas berbeda.",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1659959325_LOGO%20RESMI%20PB.png',
  },
  {
    name: 'Partai Gelombang Rakyat Indonesia (Gelora)',
    no_urut: 7,
    ig_sosmed: 'https://www.instagram.com/partaigeloraid/',
    fb_sosmed: 'https://facebook.com/https://www.facebook.com/partaigeloraindonesia/',
    x_sosmed: 'https://twitter.com/partaigeloraid',
    website: 'https://www.partaigelora.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Gelombang_Rakyat_Indonesia',
    deskripsi:"Partai Gelombang Rakyat Indonesia (disingkat Partai Gelora Indonesia) adalah partai politik di Indonesia yang didirikan pada tanggal 28 Oktober 2019.\nPartai ini didirikan oleh 99 orang dari 34 provinsi di Indonesia. Partai ini dideklarasikan dalam acara konsolidasi nasional di Jakarta, 10 November 2019. Setelah melewati proses pendaftaran dan verifikasi di Kementerian Hukum dan HAM, Partai Gelora sah menjadi badan hukum dengan penyerahan SK Menteri Hukum & HAM pada 2 Juni 2020.",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1658983159_Logo%20Gelora%20Portrait.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Keadilan Sejahtera (PKS)',
    no_urut: 8,
    ig_sosmed: 'https://instagram.com/pk_sejahtera',
    fb_sosmed: 'https://www.facebook.com/HumasPartaiKeadilanSejahtera',
    x_sosmed: 'https://twitter.com/PKSejahtera',
    website: 'https://pks.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Keadilan_Sejahtera',
    deskripsi:"Partai Keadilan Sejahtera (PKS) adalah sebuah partai politik berbasis Islam di Indonesia. Partai ini bercikal bakal dari penentangan sejumlah tokoh Islam terhadap kebijakan Presiden RI ke-2, Suharto yang mengharuskan agar tiap-tiap ormas menjadikan Pancasila sebagai asas mereka. Dari penentangan ini lahirlah gerakan-gerakan tarbiyah.Gerakan-gerakan tarbiyah ini lalu membentuk lembaga dakwah kampus yang kemudian menjadi asal usul berdirinya Partai Keadilan pada 20 Juli 1998 pasca lengsernya pemerintahan Suharto. Partai Keadilan kemudian bertransformasi menjadi Partai Keadilan Sejahtera pada tanggal 20 April 2002 akibat gagal memenuhi ambang batas parlemen sebesar 2%.PKS menjadi bagian koalisi dari pemerintahan SBY di periode tahun 2004-2009 dan 2009-2014, dan menjabat beberapa kursi menteri. Sikap PKS yang tidak keluar-keluar dari koalisi SBY meskipun kerap berlainan sikap dan melontarkan kritikan kepada pemerintahan SBY, telah membuat beberapa kalangan menilai PKS sebagai partai yang oportunis dan memanfaatkan situasi. Dalam pemilu legislatif 2019, PKS berakhir di urutan ke-7 dengan raihan suara 8,21% dan memperoleh 50 kursi. PKS menjadi oposisi selama pemerintahan Joko Widodo.\nSemenjak tahun 2019, PKS mengajukan dan memperjuangkan RUU Perlindungan Ulama dan Tokoh Agama, supaya para ulama dihormati dan dimuliakan sebagaimana Allah dan Muhammad menghormati dan memuliakan mereka. Dalam menangani pandemi Covid-19, demi meringankan kesulitan ekonomi masyarakat, PKS menganjurkan para kadernya yang mempu untuk berpoligami dengan memprioritaskan janda; namun anjuran ini kemudian dicabut setelah menuai polemik di masyarakat. Meski mendukung langkah Joko Widodo yang menolak kembalinya anggota organisasi teror, ISIS, ke Indonesia, PKS meminta agar anak-anak dari para anggota ISIS dipulangkan supaya mereka dapat dibina di Indonesia.",
    koalisi:'Perubahan',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656395115_lambang_pks.png',
    usungPaslon: 1,
  },
  {
    name: 'Partai Kebangkitan Nusantara (PKN)',
    no_urut: 9,
    ig_sosmed: 'https://www.instagram.com/pimnaspkn/',
    fb_sosmed: 'https://www.facebook.com/pimnaspkn/',
    x_sosmed: 'https://twitter.com/pimnaspkn',
    website: 'https://pimnas-pkn.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Kebangkitan_Nusantara',
    deskripsi:"Partai Kebangkitan Nusantara (disingkat PKN) adalah sebuah partai politik di Indonesia yang dideklarasikan pada tanggal 28 Oktober 2021. Ideologi partai berlandaskan pada filosofi nasional resmi Indonesia, Pancasila. Partai ini akan berpartisipasi dalam Pemilu 2024",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656155242_logo%20PKN-.png',
  },
  {
    name: 'Partai Hati Nurani Rakyat (Hanura)',
    no_urut: 10,
    ig_sosmed: 'https://www.instagram.com/dpp.hanura/',
    fb_sosmed: 'https://www.facebook.com/hatinuranirakyat',
    x_sosmed: '',
    website: 'https://partaihanura.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Hati_Nurani_Rakyat',
    deskripsi:"Partai Hati Nurani Rakyat, atau Partai Hanura, adalah sebuah partai politik di Indonesia. Jenderal TNI (Purn.) Dr. H. Wiranto Merupakan tokoh kunci berdirinya partai. Pada Pemilu 2009, partai ini bernomor urut 1. Hanura kembali lolos dalam Pemilu 2014, dan mendapat nomor urut 10. Pada Pemilu 2019, Hanura hadir sebagai peserta pemilu dengan nomor urut 13. Pada Pemilu 2024, Hanura kembali mendapat nomor urut 10.",
    koalisi:'Kerja Sama',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1659263373_hanura_10x10.png',
    usungPaslon: 3,
  },
  {
    name: 'Partai Garda Perubahan Indonesia (Garuda)',
    no_urut: 11,
    ig_sosmed: 'https://www.instagram.com/partaigaruda/',
    fb_sosmed: 'https://www.facebook.com/DPP-Partai-Garuda-105220035562924',
    x_sosmed: 'https://twitter.com/dpppartaigaruda',
    website: 'https://partaigaruda.org/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Garda_Perubahan_Indonesia',
    deskripsi:"Partai Garda Perubahan Indonesia atau Partai Garuda adalah sebuah partai politik di Indonesia. Partai Garuda dideklarasikan pada tanggal 16 April 2015. Ahmad Ridha Sabana menjabat sebagai Ketua Umum partai. Pada tahun 2015, melalui surat keputusan dari Menteri Hukum dan Hak Asasi Manusia Yasonna Laoly, Partai Garuda mendapatkan ketetapan hukum dan resmi menjadi partai politik.",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656406064_Logo%20Partai%20Garuda%20square.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Amanat Nasional (PAN)',
    no_urut: 12,
    ig_sosmed: 'https://www.instagram.com/amanatnasional/',
    fb_sosmed: 'https://web.facebook.com/amanatnasional',
    x_sosmed: 'https://twitter.com/official_PAN',
    website: 'https://pan.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Amanat_Nasional',
    deskripsi:"Partai Amanat Nasional (disingkat: PAN) adalah sebuah partai politik di Indonesia. Asas partai ini adalah Akhlak Politik Berlandaskan Agama yang Membawa Rahmat bagi Sekalian Alam (AD Bab II, Pasal 3 [2]). PAN didirikan oleh Amien Rais pada tanggal 23 Agustus 1998 berdasarkan pengesahan Depkeh HAM No. M-20.UM.06.08 tgl. 27 Agustus 2003. Ketua Umum saat ini adalah Zulkifli Hasan. Ketua Majelis Pertimbangan Partai dijabat oleh Hatta Rajasa, Tatong Bara, Yasti Soepredjo Mokoagow, sedangkan Ketua Dewan Kehormatan Partai dijabat oleh Soetrisno Bachir.",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656404797_LOGO%20PAN.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Bulan Bintang (PBB)',
    no_urut: 13,
    ig_sosmed: 'https://www.instagram.com/partaibulanbintang.official/',
    fb_sosmed: 'https://www.facebook.com/profile.php?id=100068456648409&mibextid=ZbWKwL',
    x_sosmed: 'https://twitter.com/OfficialDPP_PBB',
    website: 'https://partaibulanbintang.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Bulan_Bintang',
    deskripsi:"Partai Bulan Bintang (PBB) adalah sebuah partai politik Indonesia berasaskan modernisme Islam dan juga sebagai partai penerus Masyumi yang pernah berjaya pada masa demokrasi Liberal. Partai Bulan Bintang didirikan pada 17 Juli 1998.",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1659262742_LOGO%20PBB.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Demokrat',
    no_urut: 14,
    ig_sosmed: 'https://www.instagram.com/pdemokrat/',
    fb_sosmed: 'https://facebook.com/pdemokrat/',
    x_sosmed: 'https://twitter.com/PDemokrat',
    website: 'https://www.demokrat.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Demokrat',
    deskripsi:"Partai Demokrat atau secara umum disingkat dengan PD adalah sebuah partai politik Indonesia. Partai ini didirikan pada 9 September 2001 dan disahkan pada 27 Agustus 2003. Pendirian partai ini erat kaitannya dengan niat untuk membawa Susilo Bambang Yudhoyono, yang kala itu menjadi Menteri Koordinator bidang Politik dan Keamanan di bawah Presiden Megawati, menjadi presiden. Karena hal inilah, Partai Demokrat terkait kuat dengan figur Yudhoyono.\nPada Kongres IV Partai Demokrat yang diadakan di Hotel Shangri-La, Surabaya, 12 Mei 2015, Susilo Bambang Yudhoyono kembali terpilih menjadi Ketua Umum untuk periode 2015–2020",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656229496_WhatsApp%20Image%202022-06-26%20at%201.53.14%20PM.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Solidaritas Indonesia (PSI)',
    no_urut: 15,
    ig_sosmed: 'https://instagram.com/psi_id',
    fb_sosmed: 'https://facebook.com/psi.or.id',
    x_sosmed: 'https://twitter.com/psi.id',
    website: 'https://psi.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Solidaritas_Indonesia',
    deskripsi:"Partai Solidaritas Indonesia (disingkat PSI) adalah partai politik di Indonesia yang didirikan pasca Pemilu tahun 2014. Partai ini diketuai oleh Kaesang Pangarep sejak 25 September 2023. Partai ini cenderung mengambil target partisipan kalangan anak muda, perempuan, dan lintas agama. PSI didirikan untuk menggalang gerakan politik yang dilandasi oleh rasa solidaritas untuk kemanusiaan. Hal tersebut dikarenakan partai ini meyakini bahwa yang lebih penting dari politik adalah kemanusiaan.",
    koalisi:'Indonesia Maju',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656419883_logo-10x10.png',
    usungPaslon: 2,
  },
  {
    name: 'Partai Persatuan Indonesia (Perindo)',
    no_urut: 16,
    ig_sosmed: 'https://www.instagram.com/partaiperindo/',
    fb_sosmed: 'https://www.facebook.com/PartaiPerindo/',
    x_sosmed: 'https://twitter.com/PartaiPerindo',
    website: 'https://www.partaiperindo.com/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Persatuan_Indonesia',
    deskripsi:"Partai Persatuan Indonesia atau biasa disingkat Partai Perindo adalah sebuah partai politik di Indonesia. Partai ini didirikan oleh Hary Tanoesoedibjo, pengusaha dan pemilik perusahaan konglomerat multinasional MNC Group.\nAwalnya Perindo adalah organisasi kemasyarakatan yang dideklarasikan pada 24 Februari 2013 di Istora Senayan, Jakarta. Perindo kemudian didirikan sebagai partai politik pada tanggal 8 Oktober 2014 dan dideklarasikan pada 7 Februari 2015 di Jakarta International Expo, Kemayoran, Jakarta. Pada acara deklarasi tersebut, dihadiri oleh beberapa petinggi Koalisi Merah Putih (KMP), seperti Ketua Umum Partai Golkar Aburizal Bakrie, Ketua Umum Partai Amanat Nasional Hatta Rajasa, Presiden Partai Keadilan Sejahtera Anis Matta, dan Ketua Umum Partai Persatuan Pembangunan Djan Faridz. Selain itu juga hadir Wiranto, Ketua Umum Hanura.",
    koalisi:'Kerja Sama',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656144884_LOGO%20PARTAI%20PERINDO%2010x10%20cm%20(RGB).png',
    usungPaslon: 3,
  },
  {
    name: 'Partai Persatuan Pembangunan (PPP)',
    no_urut: 17,
    ig_sosmed: 'https://instagram.com/dpp.ppp',
    fb_sosmed: 'https://www.facebook.com/OfficialDPPPPP',
    x_sosmed: 'https://twitter.com/@DPP_PPP',
    website: 'https://www.ppp.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Persatuan_Pembangunan',
    deskripsi:"Partai Persatuan Pembangunan (disingkat PPP atau P3) adalah sebuah partai politik di Indonesia. Pada saat pendeklarasiannya pada tanggal 5 Januari 1973 partai ini merupakan hasil gabungan dari empat partai keagamaan yaitu Partai Nahdlatul Ulama (NU), Partai Islam Persatuan Tarbiyah Islamiyah (PERTI), Partai Syarikat Islam Indonesia (PSII) dan Partai Muslimin Indonesia (PARMUSI). Ketua sementara saat itu adalah Mohammad Syafa'at Mintaredja. Penggabungan keempat partai keagamaan tersebut bertujuan untuk penyederhanaan sistem kepartaian di Indonesia dalam menghadapi Pemilihan Umum pertama pada masa Orde Baru tahun 1973.",
    koalisi:'Kerja Sama',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1658455987_Logo%20PPP.png',
    usungPaslon: 3,
  },
  {
    name: 'Partai Nangroe Aceh (PNA)',
    no_urut: 18,
    ig_sosmed: '',
    fb_sosmed: '',
    x_sosmed: '',
    website: '',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Nanggroe_Aceh',
    deskripsi:"Partai Nanggroe Aceh (disingkat PNA) adalah salah satu partai politik lokal di provinsi Aceh, Indonesia. Sebelum tahun 2017, partai ini bernama Partai Nasional Aceh. Partai ini mulai ikut dalam Pemilihan umum legislatif Indonesia 2014 dan pemilihan anggota parlemen daerah Provinsi Aceh.Partai ini didirikan pada 24 April 2012 oleh Gubernur Aceh 2007-2012 Irwandi Yusuf. Pada saat pendaftaran itu, Irwandi Yusuf sendiri tidak hadir. Mereka yang datang ke Kanwil Depkumham Aceh untuk menyerahkan dokumen persyaratan pendirian partai antara lain, Irwansyah alias Teungku Mukhsalmina (Mantan Panglima GAM Aceh Rayeuk), Muharram Idris (mantan Ketua KPA Aceh Rayeuk), Ligadinsyah (mantan juru bicara Partai Aceh/mantan Panglima GAM Linge), Amni bin Ahmad Marzuki (mantan juru runding GAM), Tarmizi, Lukman Age dan Thamren Ananda (mantan Sekjen Partai Rakyat Aceh). Proses pendaftaran ditandai dengan penyerahan dokumen kelengkapan persyaratan yang dilakukan oleh Mukhsalmina dan diterima oleh Kepala Divisi Administrasi pada Kanwail Depkumham Aceh, Syamsul Bahri.\nPada 2 Mei 2017, PNA ini mengubah namanya yang awalnya Partai Nasional Aceh menjadi Partai Nanggroe Aceh karena pada Pileg 2014 partai tersebut tidak berhasil memperoleh suara maksimal yang dipersyaratkan oleh aturan ambang batas pemilu 2019. Sehingga didaftarkan lagi ke Kementerian Hukum dan HAM pada Juni 2017 dan disahkan dalam dokumen SK Kemenkunham W1-306.AH.11.01 Tahun 2017",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1657205782_PNA.png',
  },
  {
    name: 'Partai Generasi Atjeh Beusaboh Tha\'at Dan Taqwa (Gabthat)',
    no_urut: 19,
    ig_sosmed: '',
    fb_sosmed: '',
    x_sosmed: '',
    website: '',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Gabthat',
    deskripsi:"Partai Generasi Aceh Bersatu Taat dan Takwa (Aceh: Peureute Geuneurasi Atjeh Beusaboh Thaat dan Taqwa, Akronim: Gabthat) adalah satu partai politik lokal di Aceh, Indonesia yang didirikan pada tahun 2007. Sebenarnya Gabthat sudah berdiri pada 4 Desember 2005, tapi belum berbentuk partai, masih berstatus yayasan pendidikan. Partai ini mendaftar Pemilihan umum legislatif Indonesia 2009, 2019 namun tidak lolos verifikasi.\nPada pemilihan umum legislatif Indonesia 2024 partai Gabthat mendapatkan nomor urut 19.",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656604360_BENDERA.png',
  },
  {
    name: 'Partai Darul Aceh (PDA)',
    no_urut: 20,
    ig_sosmed: '',
    fb_sosmed: '',
    x_sosmed: '',
    website: 'https://www.partaidarulaceh.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Darul_Aceh',
    deskripsi:"Partai Darul Aceh (PDA) adalah salah satu partai politik lokal di provinsi Aceh, Indonesia. Partai ini ikut dalam Pemilihan umum legislatif Indonesia 2009, 2014, 2019, 2024 dan pemilihan anggota parlemen daerah Provinsi Aceh.Partai Darul Aceh merupakan satu dari tiga partai lokal di Aceh yang lolos untuk mengikuti pemilu legislatif 2014. Sebelumnya Partai Darul Aceh (PDA) menyerahkan berkas pendaftaran sebagai peserta pemilu 2012 ke Komisi Independen Pemilihan (KIP) Aceh, Selasa 4 September 2012. \nPartai Darul Aceh sebenarnya bukan partai lokal baru. Partai Darul Aceh berdiri pada tahun 2007 sebagai Partai Daulat Aceh. Karena Partai Daulat Aceh tidak mencapai perolehan suara batas minimal untuk bisa mengikuti pemilu berikutnya, sehingga Partai Daulat Aceh diganti namanya menjadi Partai Damai Aceh.\nPada Januari 2016, PDA mengubah kembali namanya yang awalnya Partai Damai Aceh menjadi Partai Daerah Aceh karena pada Pileg 2014 partai tersebut tidak berhasil memperoleh suara maksimal yang dipersyaratkan oleh aturan ambang batas pemilu 2019. Sehingga didaftarkan lagi ke Kementerian Hukum dan HAM pada 31 Oktober 2017 dan disahkan dalam dokumen SK Kemenkunham W.1-864.AH.11.01 Tahun 2016Dikarenakan kembali tidak mencapai electoral threshold bagi partai lokal untuk membentuk satu fraksi di DPRA, PDA kembali mengubah namanya yang awalnya Partai Daerah Aceh menjadi Partai Darul Aceh pada September 2021. Perubahan ini tertuang dalam SK Kemenkumham Kantor Wilayah Aceh yang dikeluarkan di Banda Aceh pada 1 November 2021",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1658110917_Gambar%20Partai%20Darul%20Aceh.png',
  },
  {
    name: 'Partai Aceh',
    no_urut: 21,
    ig_sosmed: 'https://www.instagram.com/dpa_partaiaceh',
    fb_sosmed: 'https://www.facebook.com/partai.atjeh',
    x_sosmed: 'https://twitter.com/dpp_partaiaceh',
    website: 'https://www.partaiaceh.org/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Aceh',
    deskripsi:"Partai Aceh adalah salah satu partai politik lokal di provinsi Aceh. Partai ini pertama kali mengikuti pemilihan umum saat Pemilu Legislatif  2009 dan menjadi partai pemenang di Aceh saat itu dengan perolehan suara sebesar 46,91%.Partai Aceh dahulu bernama Partai Gerakan Aceh Merdeka (GAM), kemudian pernah berubah menjadi Partai Gerakan Aceh Mandiri.\nDalam Pemilu 2009, Partai Aceh meraih suara mayoritas di Provinsi Aceh dengan menguasai 47 % suara parlemen dengan meraih 33 kursi dari 69 kursi di DPRA, namun pada pemilu 2014 hanya mampu merebut 29 kursi dari 81 kursi. Namun dalam Pemilihan umum legislatif Indonesia 2019, Komisi Independen Pemilihan (KIP) menetapkan Partai Aceh sebagai partai politik lokal yang meraih kursi terbanyak meski harus kehilangan 11 kursi di Dewan Perwakilan Rakyat Aceh (DPRA) daripada pemilu sebelumnya, sekarang mendapat 18 kursi dari 81 kursi DPRA.",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1659435873_LAMBANG%20PARTAI%20ACEH.png',
  },
  {
    name: 'Partai Adil Sejahtera Aceh (PAS Aceh)',
    no_urut: 22,
    ig_sosmed: 'https://www.instagram.com/pas.aceh_official/',
    fb_sosmed: '',
    x_sosmed: '',
    website: 'https://pas-aceh.com/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Adil_Sejahtera_Aceh',
    deskripsi:"Partai Adil Sejahtera (PAS Aceh) adalah satu partai politik lokal Aceh di Indonesia yang dirintis pada tahun 2021. Pendirian PAS Aceh merupakan salah satu rekomendasi hasil Ijtima’ Ulama Aceh dalam Silaturahmi Ulama Aceh (SUA) pada 10 November 2021 di Banda Aceh. Partai ini secara resmi dideklarasikan pada 22 Februari 2023. Pernyataan kelahirannya saat itu dibacakan langsung oleh Abuya Mawardi Waly al-Khalidy.Partai yang berbasis dayah ini merupakan salah satu partai politik peserta Pemilihan umum legislatif Indonesia 2024. Pada pemilihan umum legislatif Indonesia 2024, PAS Aceh mendapatkan nomor urut 22.",
    koalisi:'',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Logo_PAS_ACEH.webp',
  },
  {
    name: 'Partai Soliditas Independent Rakyat Aceh (SIRA)',
    no_urut: 23,
    ig_sosmed: 'https://www.instagram.com/partai_sira/',
    fb_sosmed: 'https://www.facebook.com/profile.php?id=100022436165619',
    x_sosmed: '',
    website: 'https://www.partaisira.org/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_SIRA',
    deskripsi:"Partai Soliditas Independen Rakyat Aceh (SIRA) adalah satu partai politik lokal di Aceh. Partai SIRA lahir dari perjuangan panjang seluruh rakyat Aceh yang menuntut keadilan dan kesejahteraan. Pembentukan Partai SIRA diinisiasi oleh para tokoh aktivis sipil organisasi Sentral Informasi Referendum Aceh, tahun 1999.Partai SIRA diproklamasikan di Banda Aceh pada 10 Desember 2007 bertepatan dengan Hari HAM Dunia.Partai SIRA ikut dalam Pemilihan Umum Legislatif Indonesia 2009, 2024 dan pemilihan anggota parlemen daerah Provinsi Aceh.\nPartai SIRA mempunyai kepanjangan Partai Suara Independen Rakyat Aceh. Pada kongres II diubah menjadi Partai Soliditas Independen Rakyat Aceh.",
    koalisi:'',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1659823143_Logo%20Partai%2010x10%20cm%20unk%20SIPOL_PNG.png',
  },
  {
    name: 'Partai Ummat',
    no_urut: 24,
    ig_sosmed: 'https://www.instagram.com/partaiummatofficial',
    fb_sosmed: '',
    x_sosmed: 'https://twitter.com/dpp_partaiummat',
    website: 'https://partaiummat.id/id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Ummat',
    deskripsi:"Partai Ummat, atau secara umum disingkat dengan PU adalah partai politik berbasis Islam di Indonesia yang didirikan oleh seorang politikus senior, Muhammad Amien Rais. Partai Ummat telah terdaftar dan disahkan oleh Kementerian Hukum dan Hak Asasi Manusia Republik Indonesia pada 20 Agustus 2021.",
    koalisi:'Perubahan',
    foto: 'https://infopemilu.kpu.go.id/berkas-sipol/parpol/profil/gambar_parpol/1656157120_LOGO%20PARTAI%20UMMAT%2010X10%20CM%20KPU.png',
    usungPaslon: 1,
  },
];

async function seedPartaiInfos() {
  try {
    // Remove existing documents in the collection (optional)
    await PartaiInfo.deleteMany();

    // Insert the data into the collection
    await PartaiInfo.insertMany(partaiInfoData);

    console.log('PartaiInfos successfully seeded.');
  } catch (error) {
    console.error('Error seeding PartaiInfos:', error);
  }
}

export { seedPartaiInfos };
