import PartaiInfo from '../models/partaiInfo.js';
import dotenv from 'dotenv';
dotenv.config();

const partaiInfoData = [
  {
    name: 'Partai Kebangkitan Bangsa (PKB)',
    no_urut: 1,
    ig_sosmed: 'https://www.instagram.com/pkb_id/',
    fb_sosmed: 'https://www.facebook.com/pkb.id/',
    x_sosmed: '',
    website: 'https://pkb.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Kebangkitan_Bangsa',
    foto: 'https://example.com/pkb.jpg',
  },
  {
    name: 'Partai Gerakan Indonesia Raya (Gerindra)',
    no_urut: 2,
    ig_sosmed: 'https://instagram.com/gerindra/',
    fb_sosmed: 'https://www.facebook.com/PartaiGerindra/',
    x_sosmed: 'https://twitter.com/Gerindra/',
    website: 'https://gerindra.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Gerakan_Indonesia_Raya',
    foto: 'https://example.com/gerindra.jpg',
  },
  {
    name: 'Partai Demokrasi Indonesia Perjuangan (PDI-P)',
    no_urut: 3,
    ig_sosmed: 'https://instagram.com/pdiperjuangan',
    fb_sosmed: 'https://www.facebook.com/PDI.Perjuangan.Official/',
    x_sosmed: 'https://twitter.com/PDIPerjuangan',
    website: 'https://pdiperjuangan.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Demokrasi_Indonesia_Perjuangan',
    foto: 'https://example.com/pdip.jpg',
  },
  {
    name: 'Partai Golongan Karya (Golkar)',
    no_urut: 4,
    ig_sosmed: 'https://www.instagram.com/golkar.indonesia/',
    fb_sosmed: 'https://www.facebook.com/golkar.indonesia/',
    x_sosmed: 'https://twitter.com/golkar_id/',
    website: 'https://www.partaigolkar.com/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Golongan_Karya',
    foto: 'https://example.com/golkar.jpg',
  },
  {
    name: 'Partai Nasional Demokrat (NasDem)',
    no_urut: 5,
    ig_sosmed: 'https://www.instagram.com/official_nasdem/',
    fb_sosmed: 'https://www.facebook.com/OfficialNasDem/',
    x_sosmed: 'https://twitter.com/NasDem',
    website: 'https://nasdem.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Nasional_Demokrat',
    foto: 'https://example.com/nasdem.jpg',
  },
  {
    name: 'Partai Buruh',
    no_urut: 6,
    ig_sosmed: 'https://www.instagram.com/partaiburuh_/',
    fb_sosmed: 'https://www.facebook.com/partaiburuh.official/',
    x_sosmed: 'https://twitter.com/EXCOPARTAIBURUH',
    website: 'https://partaiburuh.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Buruh_(Indonesia)',
    foto: 'https://example.com/nasdem.jpg',
  },
  {
    name: 'Partai Gelombang Rakyat Indonesia (Gelora)',
    no_urut: 7,
    ig_sosmed: 'https://www.instagram.com/partaigeloraid/',
    fb_sosmed: 'https://facebook.com/https://www.facebook.com/partaigeloraindonesia/',
    x_sosmed: 'https://twitter.com/partaigeloraid',
    website: 'https://www.partaigelora.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Gelombang_Rakyat_Indonesia',
    foto: 'https://example.com/gelora.jpg',
  },
  {
    name: 'Partai Keadilan Sejahtera (PKS)',
    no_urut: 8,
    ig_sosmed: 'https://instagram.com/pk_sejahtera',
    fb_sosmed: 'https://www.facebook.com/HumasPartaiKeadilanSejahtera',
    x_sosmed: 'https://twitter.com/PKSejahtera',
    website: 'https://pks.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Keadilan_Sejahtera',
    foto: 'https://example.com/pks.jpg',
  },
  {
    name: 'Partai Kebangkitan Nusantara (PKN)',
    no_urut: 9,
    ig_sosmed: 'https://www.instagram.com/pimnaspkn/',
    fb_sosmed: 'https://www.facebook.com/pimnaspkn/',
    x_sosmed: 'https://twitter.com/pimnaspkn',
    website: 'https://pimnas-pkn.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Kebangkitan_Nusantara',
    foto: 'https://example.com/pkn.jpg',
  },
  {
    name: 'Partai Hati Nurani Rakyat (Hanura)',
    no_urut: 10,
    ig_sosmed: 'https://www.instagram.com/dpp.hanura/',
    fb_sosmed: 'https://www.facebook.com/hatinuranirakyat',
    x_sosmed: '',
    website: 'https://partaihanura.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Hati_Nurani_Rakyat',
    foto: 'https://example.com/hanura.jpg',
  },
  {
    name: 'Partai Garda Perubahan Indonesia (Garuda)',
    no_urut: 11,
    ig_sosmed: 'https://www.instagram.com/partaigaruda/',
    fb_sosmed: 'https://www.facebook.com/DPP-Partai-Garuda-105220035562924',
    x_sosmed: 'https://twitter.com/dpppartaigaruda',
    website: 'https://partaigaruda.org/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Garda_Perubahan_Indonesia',
    foto: 'https://example.com/garuda.jpg',
  },
  {
    name: 'Partai Amanat Nasional (PAN)',
    no_urut: 12,
    ig_sosmed: 'https://www.instagram.com/amanatnasional/',
    fb_sosmed: 'https://web.facebook.com/amanatnasional',
    x_sosmed: 'https://twitter.com/official_PAN',
    website: 'https://pan.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Amanat_Nasional',
    foto: 'https://example.com/pan.jpg',
  },
  {
    name: 'Partai Bulan Bintang (PBB)',
    no_urut: 13,
    ig_sosmed: 'https://www.instagram.com/partaibulanbintang.official/',
    fb_sosmed: 'https://www.facebook.com/profile.php?id=100068456648409&mibextid=ZbWKwL',
    x_sosmed: 'https://twitter.com/OfficialDPP_PBB',
    website: 'https://partaibulanbintang.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Bulan_Bintang',
    foto: 'https://example.com/pbb.jpg',
  },
  {
    name: 'Partai Demokrat',
    no_urut: 14,
    ig_sosmed: 'https://www.instagram.com/pdemokrat/',
    fb_sosmed: 'https://facebook.com/pdemokrat/',
    x_sosmed: 'https://twitter.com/PDemokrat',
    website: 'https://www.demokrat.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Demokrat',
    foto: 'https://example.com/demokrat.jpg',
  },
  {
    name: 'Partai Solidaritas Indonesia (PSI)',
    no_urut: 15,
    ig_sosmed: 'https://instagram.com/psi_id',
    fb_sosmed: 'https://facebook.com/psi.or.id',
    x_sosmed: 'https://twitter.com/psi.id',
    website: 'https://psi.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Solidaritas_Indonesia',
    foto: 'https://example.com/psi.jpg',
  },
  {
    name: 'Partai Persatuan Indonesia (Perindo)',
    no_urut: 16,
    ig_sosmed: 'https://www.instagram.com/partaiperindo/',
    fb_sosmed: 'https://www.facebook.com/PartaiPerindo/',
    x_sosmed: 'https://twitter.com/PartaiPerindo',
    website: 'https://www.partaiperindo.com/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Persatuan_Indonesia',
    foto: 'https://example.com/perindo.jpg',
  },
  {
    name: 'Partai Persatuan Pembangunan (PPP)',
    no_urut: 17,
    ig_sosmed: 'https://instagram.com/dpp.ppp',
    fb_sosmed: 'https://www.facebook.com/OfficialDPPPPP',
    x_sosmed: 'https://twitter.com/@DPP_PPP',
    website: 'https://www.ppp.or.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Persatuan_Pembangunan',
    foto: 'https://example.com/ppp.jpg',
  },
  {
    name: 'Partai Nangroe Aceh (PNA)',
    no_urut: 18,
    ig_sosmed: '',
    fb_sosmed: '',
    x_sosmed: '',
    website: '',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Nanggroe_Aceh',
    foto: 'https://example.com/pna.jpg',
  },
  {
    name: 'Partai Generasi Atjeh Beusaboh Tha\'at Dan Taqwa (Gabthat)',
    no_urut: 19,
    ig_sosmed: '',
    fb_sosmed: '',
    x_sosmed: '',
    website: '',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Gabthat',
    foto: 'https://example.com/gabthat.jpg',
  },
  {
    name: 'Partai Darul Aceh (PDA)',
    no_urut: 20,
    ig_sosmed: '',
    fb_sosmed: '',
    x_sosmed: '',
    website: 'https://www.partaidarulaceh.id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Darul_Aceh',
    foto: 'https://example.com/pda.jpg',
  },
  {
    name: 'Partai Aceh',
    no_urut: 21,
    ig_sosmed: 'https://www.instagram.com/dpa_partaiaceh',
    fb_sosmed: 'https://www.facebook.com/partai.atjeh',
    x_sosmed: 'https://twitter.com/dpp_partaiaceh',
    website: 'https://www.partaiaceh.org/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Aceh',
    foto: 'https://example.com/pa.jpg',
  },
  {
    name: 'Partai Adil Sejahtera Aceh (PAS Aceh)',
    no_urut: 22,
    ig_sosmed: 'https://www.instagram.com/pas.aceh_official/',
    fb_sosmed: '',
    x_sosmed: '',
    website: 'https://pas-aceh.com/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Adil_Sejahtera_Aceh',
    foto: 'https://example.com/pas.jpg',
  },
  {
    name: 'Partai Soliditas Independent Rakyat Aceh (SIRA)',
    no_urut: 23,
    ig_sosmed: 'https://www.instagram.com/partai_sira/',
    fb_sosmed: 'https://www.facebook.com/profile.php?id=100022436165619',
    x_sosmed: '',
    website: 'https://www.partaisira.org/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_SIRA',
    foto: 'https://example.com/sira.jpg',
  },
  {
    name: 'Partai Ummat',
    no_urut: 24,
    ig_sosmed: 'https://www.instagram.com/partaiummatofficial',
    fb_sosmed: '',
    x_sosmed: 'https://twitter.com/dpp_partaiummat',
    website: 'https://partaiummat.id/id/',
    url_api_wikipedia: 'https://id.wikipedia.org/w/api.php?format=json&action=parse&page=Partai_Ummat',
    foto: 'https://example.com/partaiummat.jpg',
  },
];

async function seedPartaiInfos() {
  try {
    // Remove existing documents in the collection (optional)
    await PartaiInfo.deleteMany();

    // Insert the data into the collection
    await PartaiInfo.insertMany(partaiInfoData);

    console.log('PartaiInfos successfully seeded.');
  } catch (error) {
    console.error('Error seeding PartaiInfos:', error);
  }
}

export { seedPartaiInfos };
